name: Build web Image

on:
  schedule:
    - cron: '0 19 * * *'
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'web/**'

permissions:
  contents: read
  packages: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux/amd64
            label: amd64
          - platform: linux/arm64
            label: arm
    runs-on: [self-hosted, "${{ matrix.label }}"]

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Log in to the Github Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        id: build
        with:
          context: "{{defaultContext}}:web"
          platforms: ${{ matrix.platform }}
          provenance: false # https://github.com/docker/build-push-action/issues/755, https://github.com/orgs/community/discussions/45969
          sbom: false
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/mcsm-web:${{ matrix.label }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  merge:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Log in to the Github Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge manifests
        run: |
          docker manifest create ghcr.io/${{ github.repository_owner }}/mcsm-web:latest \
            ghcr.io/${{ github.repository_owner }}/mcsm-web:amd64 \
            ghcr.io/${{ github.repository_owner }}/mcsm-web:arm
          docker manifest push ghcr.io/${{ github.repository_owner }}/mcsm-web:latest
  
  mirror:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Log in to the Github Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Login to Aliyun Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Push to Aliyun Container Registry
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/mcsm-web:latest
          docker tag ghcr.io/${{ github.repository_owner }}/mcsm-web:latest ${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAMESPACE }}/mcsm-web:latest
          docker push ${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAMESPACE }}/mcsm-web:latest
